services:
  telegramwebproxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: ${BRANCH:-master}
        REPO_URL: ${REPO_URL:-https://github.com/Ajaxy/telegram-tt.git}
    image: telegram-tt:latest
    container_name: telegram-tt
    restart: unless-stopped
    ports:
      - "${PORT:-5002}:80"
