services:
  telegramwebproxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: ${BRANCH:-master}
        REPO_URL: ${REPO_URL:-https://github.com/Ajaxy/telegram-tt.git}
    image: telegram-tt:latest
    container_name: telegram-tt
    restart: unless-stopped
    ports:
      - "127.0.0.1:5002:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
