services:
  telegramwebproxy:
    image: ghcr.io/v-seti-vpn/telegram_web_proxy:latest
    container_name: telegram-tt
    restart: unless-stopped
    ports:
      - "127.0.0.1:5002:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
